### ISSUE TITLE
RuntimeError: size mismatch, m1: [16 x 3072], m2: [4096 x 1024]

### ISSUE THREAD

**Issue by Peng-KG** [why2011btv/JointConstrainedLearning#2]
When l input 'nohup python3 main_aug.py gpu_0 batch_16 0.0000001 1207_0.rst epoch_40 MATRES add_loss_1 finetune_1',it run error with 'RuntimeError: size mismatch, m1: [16 x 3072], m2: [4096 x 1024]'.
But l run code with "nohup python3 main_aug.py gpu_1 batch_500 0.001 1208_1.rst epoch_40 MATRES add_loss_1 finetune_0",it 's
OK.
It seems that it 's wrong with finetune.
Have you ever had the same problem? Could you please help me to solve it  ?

**Comment by why2011btv** [comment]
Unfortunately I do not know why either. Yet I have updated some of my code recently and it is working perfectly from my side. Probably you may need to take a look at the environment setup. Could you please try again on the new version and let me know? Thanks!
